/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Map } from "./Map";
import { MapCountArgs } from "./MapCountArgs";
import { MapFindManyArgs } from "./MapFindManyArgs";
import { MapFindUniqueArgs } from "./MapFindUniqueArgs";
import { CreateMapArgs } from "./CreateMapArgs";
import { UpdateMapArgs } from "./UpdateMapArgs";
import { DeleteMapArgs } from "./DeleteMapArgs";
import { PointOfInterestFindManyArgs } from "../../pointOfInterest/base/PointOfInterestFindManyArgs";
import { PointOfInterest } from "../../pointOfInterest/base/PointOfInterest";
import { RouteFindManyArgs } from "../../route/base/RouteFindManyArgs";
import { Route } from "../../route/base/Route";
import { MapCreateInput } from "./MapCreateInput";
import { MapService } from "../map.service";
@graphql.Resolver(() => Map)
export class MapResolverBase {
  constructor(protected readonly service: MapService) {}

  async _mapsMeta(
    @graphql.Args() args: MapCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Map])
  async maps(@graphql.Args() args: MapFindManyArgs): Promise<Map[]> {
    return this.service.maps(args);
  }

  @graphql.Query(() => Map, { nullable: true })
  async map(@graphql.Args() args: MapFindUniqueArgs): Promise<Map | null> {
    const result = await this.service.map(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Map)
  async createMap(@graphql.Args() args: CreateMapArgs): Promise<Map> {
    return await this.service.createMap({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Map)
  async updateMap(@graphql.Args() args: UpdateMapArgs): Promise<Map | null> {
    try {
      return await this.service.updateMap({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Map)
  async deleteMap(@graphql.Args() args: DeleteMapArgs): Promise<Map | null> {
    try {
      return await this.service.deleteMap(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [PointOfInterest], { name: "pointOfInterests" })
  async findPointOfInterests(
    @graphql.Parent() parent: Map,
    @graphql.Args() args: PointOfInterestFindManyArgs
  ): Promise<PointOfInterest[]> {
    const results = await this.service.findPointOfInterests(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Route], { name: "routes" })
  async findRoutes(
    @graphql.Parent() parent: Map,
    @graphql.Args() args: RouteFindManyArgs
  ): Promise<Route[]> {
    const results = await this.service.findRoutes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.Mutation(() => Map)
  async ImportMap(
    @graphql.Args()
    args: MapCreateInput
  ): Promise<Map> {
    return this.service.ImportMap(args);
  }
}
