/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { StringFilter } from "../../util/StringFilter";
import { PointOfInterestListRelationFilter } from "../../pointOfInterest/base/PointOfInterestListRelationFilter";
import { RouteListRelationFilter } from "../../route/base/RouteListRelationFilter";

@InputType()
class MapWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  dateImportation?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  fichier?: JsonFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nom?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PointOfInterestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PointOfInterestListRelationFilter)
  @IsOptional()
  @Field(() => PointOfInterestListRelationFilter, {
    nullable: true,
  })
  pointOfInterests?: PointOfInterestListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RouteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RouteListRelationFilter)
  @IsOptional()
  @Field(() => RouteListRelationFilter, {
    nullable: true,
  })
  routes?: RouteListRelationFilter;
}

export { MapWhereInput as MapWhereInput };
