/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PlageDeCellulesService } from "../plageDeCellules.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PlageDeCellulesCreateInput } from "./PlageDeCellulesCreateInput";
import { PlageDeCellules } from "./PlageDeCellules";
import { PlageDeCellulesFindManyArgs } from "./PlageDeCellulesFindManyArgs";
import { PlageDeCellulesWhereUniqueInput } from "./PlageDeCellulesWhereUniqueInput";
import { PlageDeCellulesUpdateInput } from "./PlageDeCellulesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PlageDeCellulesControllerBase {
  constructor(
    protected readonly service: PlageDeCellulesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PlageDeCellules })
  @nestAccessControl.UseRoles({
    resource: "PlageDeCellules",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPlageDeCellules(
    @common.Body() data: PlageDeCellulesCreateInput
  ): Promise<PlageDeCellules> {
    return await this.service.createPlageDeCellules({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PlageDeCellules] })
  @ApiNestedQuery(PlageDeCellulesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PlageDeCellules",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async plageDeCellulesItems(
    @common.Req() request: Request
  ): Promise<PlageDeCellules[]> {
    const args = plainToClass(PlageDeCellulesFindManyArgs, request.query);
    return this.service.plageDeCellulesItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PlageDeCellules })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlageDeCellules",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async plageDeCellules(
    @common.Param() params: PlageDeCellulesWhereUniqueInput
  ): Promise<PlageDeCellules | null> {
    const result = await this.service.plageDeCellules({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PlageDeCellules })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlageDeCellules",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePlageDeCellules(
    @common.Param() params: PlageDeCellulesWhereUniqueInput,
    @common.Body() data: PlageDeCellulesUpdateInput
  ): Promise<PlageDeCellules | null> {
    try {
      return await this.service.updatePlageDeCellules({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PlageDeCellules })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlageDeCellules",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePlageDeCellules(
    @common.Param() params: PlageDeCellulesWhereUniqueInput
  ): Promise<PlageDeCellules | null> {
    try {
      return await this.service.deletePlageDeCellules({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
