/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Diagramme } from "./Diagramme";
import { DiagrammeCountArgs } from "./DiagrammeCountArgs";
import { DiagrammeFindManyArgs } from "./DiagrammeFindManyArgs";
import { DiagrammeFindUniqueArgs } from "./DiagrammeFindUniqueArgs";
import { DeleteDiagrammeArgs } from "./DeleteDiagrammeArgs";
import { DiagrammeService } from "../diagramme.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Diagramme)
export class DiagrammeResolverBase {
  constructor(
    protected readonly service: DiagrammeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Diagramme",
    action: "read",
    possession: "any",
  })
  async _diagrammesMeta(
    @graphql.Args() args: DiagrammeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Diagramme])
  @nestAccessControl.UseRoles({
    resource: "Diagramme",
    action: "read",
    possession: "any",
  })
  async diagrammes(
    @graphql.Args() args: DiagrammeFindManyArgs
  ): Promise<Diagramme[]> {
    return this.service.diagrammes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Diagramme, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Diagramme",
    action: "read",
    possession: "own",
  })
  async diagramme(
    @graphql.Args() args: DiagrammeFindUniqueArgs
  ): Promise<Diagramme | null> {
    const result = await this.service.diagramme(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Diagramme)
  @nestAccessControl.UseRoles({
    resource: "Diagramme",
    action: "delete",
    possession: "any",
  })
  async deleteDiagramme(
    @graphql.Args() args: DeleteDiagrammeArgs
  ): Promise<Diagramme | null> {
    try {
      return await this.service.deleteDiagramme(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
