/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Taux } from "./Taux";
import { TauxCountArgs } from "./TauxCountArgs";
import { TauxFindManyArgs } from "./TauxFindManyArgs";
import { TauxFindUniqueArgs } from "./TauxFindUniqueArgs";
import { DeleteTauxArgs } from "./DeleteTauxArgs";
import { TauxService } from "../taux.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Taux)
export class TauxResolverBase {
  constructor(
    protected readonly service: TauxService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Taux",
    action: "read",
    possession: "any",
  })
  async _tauxesMeta(
    @graphql.Args() args: TauxCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Taux])
  @nestAccessControl.UseRoles({
    resource: "Taux",
    action: "read",
    possession: "any",
  })
  async tauxes(@graphql.Args() args: TauxFindManyArgs): Promise<Taux[]> {
    return this.service.tauxes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Taux, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Taux",
    action: "read",
    possession: "own",
  })
  async taux(@graphql.Args() args: TauxFindUniqueArgs): Promise<Taux | null> {
    const result = await this.service.taux(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Taux)
  @nestAccessControl.UseRoles({
    resource: "Taux",
    action: "delete",
    possession: "any",
  })
  async deleteTaux(@graphql.Args() args: DeleteTauxArgs): Promise<Taux | null> {
    try {
      return await this.service.deleteTaux(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
